services:
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    environment:
      - NEO4J_AUTH=neo4j/password
    volumes:
      - ./neo4j/neo4j-database:/data  # Persist data
    ports:
      - "7474:7474"  # HTTP port
      - "7687:7687"  # Bolt port
    networks:
      - docker-net

  fastapi:
    build: ./backend
    container_name: fastapi
    depends_on:
      - neo4j
    ports:
      - "8000:8000"
    networks:
      - docker-net
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      
networks:
  docker-net:
    driver: bridge