# Define the Pokemon data to preload
data = [
    {"pokemon": "Ditto", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//132.png","type": "Normal", "bio": "I am a pink blob"},
    {"pokemon": "Grookey", "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRLx94R3D2o1WqiOYYQw07Z_UDCBywD-AahpQ&s","type": "Grass", "bio": "Professional Taxidermist and knife collector. Hoping to find a trainer who will help him complete his collections."},
    {"pokemon": "Malamar", "image":"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/687.png","type": "Dark/Psychic", "bio": "Mysterious, Destructive, Curious, Bizzare creature who is on a mission to reshape humanity"},
    {"pokemon": "Pikachu", "image":"https://pokemonletsgo.pokemon.com/assets/img/common/char-pikachu.png","type": "Electric", "bio": "Gets pretty tired from using their electricity to charge their phone. Blames it on their loud neighbors."},
    {"pokemon": "Charizard", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//006.png","type": "Fire/Flying", "bio": "Might looks ferocious, but has a warm heart and loves to take casual flights at night."},
    {"pokemon": "Bulbasaur", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//001.png","type": "Grass/Poison", "bio": "A real green thumb who cherishes their garden."},
    {"pokemon": "Squirtle", "image":"https://miro.medium.com/v2/resize:fit:750/1*W_ITBT0_dDNGyy_yPRQO3g.jpeg","type": "Water", "bio": "Introvert looking to break out of their shell."},
    {"pokemon": "Eevee", "image":"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/133.png","type": "Normal", "bio": "Can jump from cuddly to vicious in a moment's time. They'd give a cat a run for their money."},
    {"pokemon": "Frosslass", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//478.png","type": "Ice/Ghost", "bio": "Cold and ruthless, they are the reason paranormal occurences are chilling."},
    {"pokemon": "Mewtwo", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//150.png","type": "Psychic", "bio": "Looking for a trainer who is psychically resistant or dimwitted."},
    {"pokemon": "Lucario", "image":"https://img.pokemondb.net/artwork/large/lucario.jpg", "type": "Fighting/Steel", "bio": "Always looking for a brawl. Prone to picking fights, especially when intoxicated."},
    {"pokemon": "Snorlax", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//143.png","type": "Normal", "bio": "Narcoleptic who wishes they weren't so tired, but too sleepy to try and fix it."},
    {"pokemon": "Gengar", "image":"https://img.pokemondb.net/artwork/large/gengar.jpg","type": "Ghost/Poison", "bio": "Likes scaring friends and foes alike. Known to play pranks on anyone within a five mile radius."},
    {"pokemon": "Jigglypuff", "image":"https://img.pokemondb.net/artwork/large/jigglypuff.jpg","type": "Normal/Fairy", "bio": "Cute on the outside, a true monster on the inside. Looking for any chance to break free from the binds that hold them. "},
    {"pokemon": "Machamp", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//068.png","type": "Fighting", "bio": "Boxer during the day, expert sushi chef at night. "},
    {"pokemon": "Arcanine", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//059.png","type": "Fire", "bio": "Loves to play fetch, just don't use a stick or anything else thats flammable."},
    {"pokemon": "Dragonite", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//149.png","type": "Dragon/Flying", "bio": "Interested in learning about everything. Also a rival jokester to Gengar."},
    {"pokemon": "Blastoise", "image":"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/009.png","type": "Water", "bio": "A walking fortress and sharpshooting champ."},
    {"pokemon": "Venusaur", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//003.png","type": "Grass/Poison", "bio": "They've mastered the hobbyist's garden, growing board with simple flora. Now cultivates potent poisons and concoctions."},
    {"pokemon": "Lugia", "image":"https://img.pokemondb.net/artwork/large/lugia.jpg","type": "Psychic/Flying", "bio": "Their large hands give them an upperhand in slap boxing."},
    {"pokemon": "Ho-Oh", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//250.png","type": "Psychic/Flying", "bio": "Wanted in 9 provinces for flying in restricted airspaces."},
    {"pokemon": "Umbreon", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//197.png","type": "Fire/Flying", "bio": "Always trying out the new hottest foods on the maret and makes sure you know about it."},
    {"pokemon": "Espeon", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//196.png","type": "Psychic", "bio": "Uses telepathy beg for food or tell the worst puns imaginable."},
    {"pokemon": "Sylveon", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//700.png","type": "Fairy", "bio": "Happy-go-lucky and never a fair-weather friend."},
    {"pokemon": "Gyrados", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//130.png","type": "Water/Flying", "bio": "Overnight transformation from Guppy to sea god has left them looking for new clothes. Still torn about their favorite jacket."},
    {"pokemon": "Alakazam", "image":"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/065.png","type": "Psychic", "bio": "Has immense pyschic power, but still cannot figure out how to pull a rabbit from a hat."},
    {"pokemon": "Tyranitar", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//248.png","type": "Rock/Dark", "bio": "Once mistaken for Godzilla. King Kong was busy, so the government brought in Grookey."},
    {"pokemon": "Garchomp", "image":"https://img.pokemondb.net/artwork/large/garchomp.jpg","type": "Dragon/Ground", "bio": "Loves to knit, but has trouble gripping their sewing needles. "},
    {"pokemon":"Metagross", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//376.png","type":"Steel/Psychic","bio":"Has the ability to fold its legs, allowing its disc shaped head to be thrown like a frisbee."},
    {"pokemon":"Scizor", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//212.png","type":"Bug/Steel","bio":"Quick and nimble, with claws like steel, there's no wonder no one wants to play tickle fight with them."},
    {"pokemon":"Infernape", "image":"https://img.pokemondb.net/artwork/large/infernape.jpg","type":"Fire/Fighting","bio":"Has a black belt in Karate and loves to ride motorcycles. Allergic to bananas."},
    {"pokemon":"Blaziken", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//257.png","type":"Fire/Fighting","bio":"Often joins rides in the sidecar one Infernape's motorcycle."},
    {"pokemon":"Greninja", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//658.png","type":"Water/Dark","bio":"Ex-blackops agent from the Cold War. Infiltrated REDACTED in REDACTED, but don't ask them about it."},
    {"pokemon":"Zoroark", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//571.png","type":"Dark","bio":"Often uses hair like a paintbrush, creating paintings much brighter than their moody attitude would imply."},
    {"pokemon":"Charmeleon", "image":"https://img.pokemondb.net/artwork/large/charmeleon.jpg","type":"Fire","bio":"Likes bouncy castles, but has trouble keeping the fire in when having too much fun."},
    {"pokemon":"Ivysaur", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//002.png","type":"Grass/Poison","bio":"Doesn't like to garden, but enjoys immersing themself in soil. Says they now know what a potato feels like."},
    {"pokemon":"Wartortle", "image":"https://img.pokemondb.net/artwork/large/wartortle.jpg","type":"Water","bio":"A lot of fight in a little package. Doesn't like for anyone to touch their shell."},
    {"pokemon":"Zapdos", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//145.png","type":"Electric/Flying","bio":"Dread follows in their wake. When one sees them roosting on the powerlines, the power grid is soon to fall."},
    {"pokemon":"Articuno", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//144.png","type":"Ice/Flying","bio":"Likes to fly through obstacle courses and holds five records in the National PokeSoar tournaments."},
    {"pokemon":"Moltres", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//146.png","type":"Fire/Flying","bio":"Flies through freezing tundras and through ice water, claiming it makes them stronger. Local PokeDoctors claim no evidence supports these claims."},
    {"pokemon":"Raichu", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//026.png","type":"Electric","bio":"Master of the flute and plays at the local tavern. Wants to learn the triangle."},
    {"pokemon":"Jolteon", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//135.png","type":"Electric","bio":"The first to be called on to fix what Zapdos breaks."},
    {"pokemon":"Vaporeon", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//134.png","type":"Water","bio":"Takes weekly swims with a family of seals. Helps cats learn to swim."},
    {"pokemon":"Flareon", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//136.png","type":"Fire","bio":"Takes pride in lighting stoves and fireplaces for families who can't find their lighters."},
    {"pokemon":"Lapras", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//131.png","type":"Water/Ice","bio":"Often mistaken for the Loch Ness Monster. Makes sure to give cryptid hunters the run-around."},
    {"pokemon":"Onix", "image":"https://static.wikia.nocookie.net/pokemongo/images/b/b2/Onix.png/revision/latest/scale-to-width/360?cb=20240212221426","type":"Rock/Ground","bio":"Amateur novelist and lover of water painting."},
    {"pokemon":"Nidoqueen", "image":"https://img.pokemondb.net/artwork/large/nidoqueen.jpg","type":"Poison/Ground","bio":"Claims to be the Queen of a lost kingdom. Likely the sovereign ruler of some pocket lint and three thumbtacks."},
    {"pokemon":"Clefairy", "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRayN5kCcBgk3a6KvwvqbnRe3AHfgAQu8C_qA&s","type":"Fairy","bio":"Arrested for poaching but plans to not get caught this time."},
    {"pokemon":"Mew", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//151.png","type":"Psychic","bio":"Is definitely not an alien. No way, no how."},
    {"pokemon":"Clefable", "image":"https://img.pokemondb.net/artwork/large/clefable.jpg", "type":"Fairy","bio":"Proud AA leader."},
    {"pokemon":"Magnezone", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//462.png", "type":"Electric/Steel","bio":"A once mediocre detective, now a mediocre PI."}
    # {"pokemon":"Volcarona", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//637.png", "type":"Bug/Fire","bio":""},
    # {"pokemon":"Heracross", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//214.png", "type":"Bug/Fighting","bio":""},
    # {"pokemon":"Rhydon", "image":"https://img.pokemondb.net/artwork/large/rhydon.jpg", "type":"Ground/Rock","bio":""},
    # {"pokemon":"Rhyperior", "image":"https://img.pokemondb.net/artwork/large/rhyperior.jpg", "type":"Ground/Rock","bio":""},
    # {"pokemon":"Togekiss", "image":"https://img.pokemondb.net/artwork/large/togekiss.jpg", "type":"Fairy/Flying","bio":""},
    # {"pokemon":"Salamence", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//373.png", "type":"Dragon/Flying","bio":""},
    # {"pokemon":"Sceptile", "image":"https://img.pokemondb.net/artwork/large/sceptile.jpg", "type":"Grass","bio":""},
    # {"pokemon":"Swampert","image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//260.png","type":"Water/Ground","bio":""},
    # {"pokemon":"Aggron", "image":"https://img.pokemondb.net/artwork/large/aggron.jpg", "type":"Steel/Rock","bio":""},
    # {"pokemon":"Altaria", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//334.png", "type":"Dragon/Flying","bio":""},
    # {"pokemon":"Flygon", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//330.png", "type":"Ground/Dragon","bio":""},
    # {"pokemon":"Mudkip", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//258.png", "type":"Water","bio":""},
    # {"pokemon":"Torchic", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//255.png", "type":"Fire","bio":""},
    # {"pokemon":"Treecko", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//252.png", "type":"Grass","bio":""},
    # {"pokemon":"Torterra", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//389.png", "type":"Grass/Ground","bio":""},
    # {"pokemon":"Empoleon", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//395.png", "type":"Water/Steel","bio":""},
    # {"pokemon":"Luxray", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//405.png", "type":"Electric","bio":""},
    # {"pokemon":"Staraptor", "image":"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/398.png", "type":"Normal/Flying","bio":""},
    # {"pokemon":"Gible", "image":"https://img.pokemondb.net/artwork/large/gible.jpg", "type":"Dragon/Ground","bio":""},
    # {"pokemon":"Piplup", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//393.png", "type":"Water","bio":""},
    # {"pokemon":"Chimchar", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//390.png", "type":"Fire","bio":""},
    # {"pokemon":"Turtwig", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//387.png", "type":"Grass","bio":""},
    # {"pokemon":"Gallade", "image":"https://img.pokemondb.net/artwork/large/gallade-mega.jpg", "type":"Psychic/Fighting","bio":""},
    # {"pokemon":"Glaceon", "image":"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/471.png", "type":"Ice","bio":""},
    # {"pokemon":"Leafeon", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//470.png", "type":"Grass","bio":""},
    # {"pokemon":"Absol", "image":"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/359.png", "type":"Dark","bio":""},
    # {"pokemon":"Crobat", "image":"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/169.png", "type":"Poison/Flying","bio":""},
    # {"pokemon":"Kingdra", "image":"https://img.pokemondb.net/artwork/large/kingdra.jpg", "type":"Water/Dragon","bio":""},
    # {"pokemon":"Slowbro", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//080.png", "type":"Water/Psychic","bio":""},
    # {"pokemon":"Slowking", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//199.png", "type":"Water/Psychic","bio":""},
    # {"pokemon":"Ampharos", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//181.png", "type":"Electric","bio":""},
    # {"pokemon":"Typhlosion", "image":"https://www.pokemon.com/static-assets/content-assets/cms2/img/pokedex/full/157.png", "type":"Fire","bio":""},
    # {"pokemon":"Feraligatr", "image":"https://img.pokemondb.net/artwork/large/feraligatr.jpg", "type":"Water","bio":""},
    # {"pokemon":"Meganium", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//154.png", "type":"Grass","bio":""},
    # {"pokemon":"Noivern", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//715.png", "type":"Flying/Dragon","bio":""},
    # {"pokemon":"Houndoom", "image":"https://img.pokemondb.net/artwork/large/houndoom.jpg", "type":"Dark/Fire","bio":""},
    # {"pokemon":"Zygarde", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//718.png", "type":"Dragon/Ground","bio":""},
    # {"pokemon":"Dialga", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//483.png", "type":"Steel/Dragon","bio":""},
    # {"pokemon":"Palkia", "image":"https://img.pokemondb.net/artwork/large/palkia.jpg", "type":"Water/Dragon","bio":""},
    # {"pokemon":"Rayquaza", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//384.png", "type":"Dragon/Flying","bio":""},
    # {"pokemon":"Deoxys", "image":"https://img.pokemondb.net/artwork/large/deoxys-normal.jpg", "type":"Psychic","bio":""},
    # {"pokemon":"Regice", "image":"https://img.pokemondb.net/artwork/large/regice.jpg", "type":"Ice","bio":""},
    # {"pokemon":"Registeel", "image":"https://archives.bulbagarden.net/media/upload/thumb/2/22/0379Registeel.png/800px-0379Registeel.png", "type":"Steel","bio":""},
    # {"pokemon":"Regirock", "image":"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQR77iUJbQtK-6MNSqa9ICgdyXCe0nrXbxqjg&s", "type":"Rock","bio":""},
    # {"pokemon":"Jirachi", "image":"https://img.pokemondb.net/artwork/large/jirachi.jpg", "type":"Steel/Psychic","bio":""},
    # {"pokemon":"Cresselia", "image":"https://img.pokemondb.net/artwork/large/cresselia.jpg", "type":"Psychic","bio":""},
    # {"pokemon":"Darkrai", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//491.png", "type":"Dark","bio":""},
    # {"pokemon":"Manaphy", "image":"https://img.pokemondb.net/artwork/large/manaphy.jpg", "type":"Water","bio":""},
    # {"pokemon":"Arceus", "image":"https://archives.bulbagarden.net/media/upload/thumb/9/9e/0493Arceus.png/640px-0493Arceus.png", "type":"Normal","bio":""},
    # {"pokemon":"Giratina", "image":"https://assets.pokemon.com/assets/cms2/img/pokedex/full//487.png", "type":"Ghost/Dragon","bio":""},
    # {"pokemon":"Victini", "image":"https://img.pokemondb.net/artwork/large/victini.jpg", "type":"Psychic/Fire","bio":""},
    # {"pokemon":"Mr.Mime", "image":"https://platform.polygon.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/16233533/Screen_Shot_2019_05_09_at_3.37.48_PM.png?quality=90&strip=all&crop=19.46764091858,0,61.064718162839,100", "type":"Psychic/Fairy","bio":""}
    
]

