# Define the Pokemon data to preload
data = [
    {"pokemon": "Ditto", "image":"https://tinyurl.com/2argum38","type": "Normal", "bio": "I am a pink blob"},
    {"pokemon": "Grookey", "image":"https://tinyurl.com/29hfofv5","type": "Grass", "bio": "Professional Taxidermist and knife collector. Hoping to find a trainer who will help him complete his collections."},
    {"pokemon": "Malamar", "image":"https://tinyurl.com/27c6bvgy","type": "Dark/Psychic", "bio": "Mysterious, Destructive, Curious, Bizzare creature who is on a mission to reshape humanity"},
    {"pokemon": "Pikachu", "image":"https://tinyurl.com/yxq8jnen","type": "Electric", "bio": "Gets pretty tired from using their electricity to charge their phone. Blames it on their loud neighbors."},
    {"pokemon": "Charizard", "image":"https://tinyurl.com/2y442klw","type": "Fire/Flying", "bio": "Might looks ferocious, but has a warm heart and loves to take casual flights at night."},
    {"pokemon": "Bulbasaur", "image":"https://tinyurl.com/2bhkbqgf","type": "Grass/Poison", "bio": "A real green thumb who cherishes their garden."},
    {"pokemon": "Squirtle", "image":"https://tinyurl.com/28845opa","type": "Water", "bio": "Introvert looking to break out of their shell."},
    {"pokemon": "Eevee", "image":"https://tinyurl.com/2dlsmw2u","type": "Normal", "bio": "Can jump from cuddly to vicious in a moment's time. They'd give a cat a run for their money."},
    {"pokemon": "Frosslass", "image":"https://tinyurl.com/22akc8bl","type": "Ice/Ghost", "bio": "Cold and ruthless, they are the reason paranormal occurences are chilling."},
    {"pokemon": "Mewtwo", "image":"https://tinyurl.com/27f5go4d","type": "Psychic", "bio": "Looking for a trainer who is psychically resistant or dimwitted."},
    {"pokemon": "Lucario", "image":"https://tinyurl.com/2xr6xnn9", "type": "Fighting/Steel", "bio": "Always looking for a brawl. Prone to picking fights, especially when intoxicated."},
    {"pokemon": "Snorlax", "image":"https://tinyurl.com/27gpzdu7","type": "Normal", "bio": "Narcoleptic who wishes they weren't so tired, but too sleepy to try and fix it."},
    {"pokemon": "Gengar", "image":"https://tinyurl.com/2c2nc9fb","type": "Ghost/Poison", "bio": "Likes scaring friends and foes alike. Known to play pranks on anyone within a five mile radius."},
    {"pokemon": "Jigglypuff", "image":"https://tinyurl.com/23v7qwqn","type": "Normal/Fairy", "bio": "Cute on the outside, a true monster on the inside. Looking for any chance to break free from the binds that hold them. "},
    {"pokemon": "Machamp", "image":"https://tinyurl.com/28qwvyyh","type": "Fighting", "bio": "Boxer during the day, expert sushi chef at night. "},
    {"pokemon": "Arcanine", "image":"https://tinyurl.com/2a8qatej","type": "Fire", "bio": "Loves to play fetch, just don't use a stick or anything else thats flammable."},
    {"pokemon": "Dragonite", "image":"https://tinyurl.com/283c2t4q","type": "Dragon/Flying", "bio": "Interested in learning about everything. Also a rival jokester to Gengar."},
    {"pokemon": "Blastoise", "image":"https://tinyurl.com/295a279a","type": "Water", "bio": "A walking fortress and sharpshooting champ."},
    {"pokemon": "Venusaur", "image":"https://tinyurl.com/273teuv2","type": "Grass/Poison", "bio": "They've mastered the hobbyist's garden, growing board with simple flora. Now cultivates potent poisons and concoctions."},
    {"pokemon": "Lugia", "image":"https://tinyurl.com/24bj4ntq","type": "Psychic/Flying", "bio": "Their large hands give them an upperhand in slap boxing."},
    {"pokemon": "Ho-Oh", "image":"https://tinyurl.com/2yrkn3aw","type": "Psychic/Flying", "bio": "Wanted in 9 provinces for flying in restricted airspaces."},
    {"pokemon": "Umbreon", "image":"https://tinyurl.com/29q2aayq","type": "Fire/Flying", "bio": "Always trying out the new hottest foods on the maret and makes sure you know about it."},
    {"pokemon": "Espeon", "image":"https://tinyurl.com/2732ydm4","type": "Psychic", "bio": "Uses telepathy beg for food or tell the worst puns imaginable."},
    {"pokemon": "Sylveon", "image":"https://tinyurl.com/25ffm28h","type": "Fairy", "bio": "Happy-go-lucky and never a fair-weather friend."},
    {"pokemon": "Gyrados", "image":"https://tinyurl.com/26pwjdto","type": "Water/Flying", "bio": "Overnight transformation from Guppy to sea god has left them looking for new clothes. Still torn about their favorite jacket."},
    {"pokemon": "Alakazam", "image":"https://tinyurl.com/257w35vy","type": "Psychic", "bio": "Has immense pyschic power, but still cannot figure out how to pull a rabbit from a hat."},
    {"pokemon": "Tyranitar", "image":"https://tinyurl.com/27lnf3gv","type": "Rock/Dark", "bio": "Once mistaken for Godzilla. King Kong was busy, so the government brought in Grookey."},
    {"pokemon": "Garchomp", "image":"https://tinyurl.com/22abpnxv","type": "Dragon/Ground", "bio": "Loves to knit, but has trouble gripping their sewing needles. "},
    {"pokemon":"Metagross", "image":"https://tinyurl.com/2bpr47dt","type":"Steel/Psychic","bio":"Has the ability to fold its legs, allowing its disc shaped head to be thrown like a frisbee."},
    {"pokemon":"Scizor", "image":"https://tinyurl.com/232u8bhd","type":"Bug/Steel","bio":"Quick and nimble, with claws like steel, there's no wonder no one wants to play tickle fight with them."},
    {"pokemon":"Infernape", "image":"https://tinyurl.com/2d2j9je8","type":"Fire/Fighting","bio":"Has a black belt in Karate and loves to ride motorcycles. Allergic to bananas."},
    {"pokemon":"Blaziken", "image":"https://tinyurl.com/24uobqf6","type":"Fire/Fighting","bio":"Often joins rides in the sidecar one Infernape's motorcycle."},
    {"pokemon":"Greninja", "image":"https://tinyurl.com/2d7m9ejx","type":"Water/Dark","bio":"Ex-blackops agent from the Cold War. Infiltrated REDACTED in REDACTED, but don't ask them about it."},
    {"pokemon":"Zoroark", "image":"https://tinyurl.com/2d4yy6ut","type":"Dark","bio":"Often uses hair like a paintbrush, creating paintings much brighter than their moody attitude would imply."},
    {"pokemon":"Charmeleon", "image":"https://tinyurl.com/y566epa3","type":"Fire","bio":"Likes bouncy castles, but has trouble keeping the fire in when having too much fun."},
    {"pokemon":"Ivysaur", "image":"https://tinyurl.com/22xqvv3n","type":"Grass/Poison","bio":"Doesn't like to garden, but enjoys immersing themself in soil. Says they now know what a potato feels like."},
    {"pokemon":"Wartortle", "image":"https://tinyurl.com/2ykhdzpm","type":"Water","bio":"A lot of fight in a little package. Doesn't like for anyone to touch their shell."},
    {"pokemon":"Zapdos", "image":"https://tinyurl.com/2cona88v","type":"Electric/Flying","bio":"Dread follows in their wake. When one sees them roosting on the powerlines, the power grid is soon to fall."},
    {"pokemon":"Articuno", "image":"https://tinyurl.com/2c2gahwr","type":"Ice/Flying","bio":"Likes to fly through obstacle courses and holds five records in the National PokeSoar tournaments."},
    {"pokemon":"Moltres", "image":"https://tinyurl.com/28d5npmk","type":"Fire/Flying","bio":"Flies through freezing tundras and through ice water, claiming it makes them stronger. Local PokeDoctors claim no evidence supports these claims."},
    {"pokemon":"Raichu", "image":"https://tinyurl.com/2ajdg4ca","type":"Electric","bio":"Master of the flute and plays at the local tavern. Wants to learn the triangle."},
    {"pokemon":"Jolteon", "image":"https://tinyurl.com/2623qblf","type":"Electric","bio":"The first to be called on to fix what Zapdos breaks."},
    {"pokemon":"Vaporeon", "image":"https://tinyurl.com/24eabj6k","type":"Water","bio":"Takes weekly swims with a family of seals. Helps cats learn to swim."},
    {"pokemon":"Flareon", "image":"https://tinyurl.com/22l39ryl","type":"Fire","bio":"Takes pride in lighting stoves and fireplaces for families who can't find their lighters."},
    {"pokemon":"Lapras", "image":"https://tinyurl.com/28ctswta","type":"Water/Ice","bio":"Often mistaken for the Loch Ness Monster. Makes sure to give cryptid hunters the run-around."},
    {"pokemon":"Onix", "image":"https://tinyurl.com/22puetd3","type":"Rock/Ground","bio":"Amateur novelist and lover of water painting."},
    {"pokemon":"Nidoqueen", "image":"https://tinyurl.com/2acopbp9","type":"Poison/Ground","bio":"Claims to be the Queen of a lost kingdom. Likely the sovereign ruler of some pocket lint and three thumbtacks."},
    {"pokemon":"Clefairy", "image":"https://tinyurl.com/2xvv6z5p","type":"Fairy","bio":"Arrested for poaching but plans to not get caught this time."},
    {"pokemon":"Mew", "image":"https://tinyurl.com/23k63mge","type":"Psychic","bio":"Is definitely not an alien. No way, no how."},
    {"pokemon":"Clefable", "image":"https://tinyurl.com/25m7v7vd", "type":"Fairy","bio":"Proud AA leader."},
    {"pokemon":"Magnezone", "image":"https://tinyurl.com/2bf7e8gd", "type":"Electric/Steel","bio":"A once mediocre detective, now a mediocre PI."},
    {"pokemon":"Volcarona", "image":"https://tinyurl.com/2xk8mskz", "type":"Bug/Fire","bio":"Loves to make lightshows with fiery cocoons and bioluminescent thread."},
    {"pokemon":"Heracross", "image":"https://tinyurl.com/298gomw5", "type":"Bug/Fighting","bio":"Found their fortune working the mines. Heracross 1, Black Lung 0"},
    {"pokemon":"Rhydon", "image":"https://tinyurl.com/y3gm6hsw", "type":"Ground/Rock","bio":"Is a favored bouncer at various bars for their hulking stature."},
    {"pokemon":"Rhyperior", "image":"https://tinyurl.com/24k86zyr", "type":"Ground/Rock","bio":"Works with PMCs to carve through rough terrain and blockades."},
    {"pokemon":"Togekiss", "image":"https://tinyurl.com/2xs85vpj", "type":"Fairy/Flying","bio":"High altitude scout known for their sneaky flights through the clouds."},
    {"pokemon":"Salamence", "image":"https://tinyurl.com/28nk3mau", "type":"Dragon/Flying","bio":"Long drempt of growing wings and flying. Still working on the flying part."},
    {"pokemon":"Sceptile", "image":"https://tinyurl.com/24y23w64", "type":"Grass","bio":"Adept navigator of Pokemon high society. Owns way too many statues of themself."},
    {"pokemon":"Swampert","image":"https://tinyurl.com/28ntrlx8","type":"Water/Ground","bio":"Stalks the muddy bogs and mires in search of prey. They favor hunting lost travelers, earning them a hefty bounty price on their head."},
    {"pokemon":"Aggron", "image":"https://tinyurl.com/2nal6nd2", "type":"Steel/Rock","bio":"Shrouded in mystery, the only sign of their movements is the terror left in their wake."},
    {"pokemon":"Altaria", "image":"https://tinyurl.com/236g9kvv", "type":"Dragon/Flying","bio":"Spends most of their time staring at the bobbing of their drinking bird toy."},
    {"pokemon":"Flygon", "image":"https://tinyurl.com/229cfc5t", "type":"Ground/Dragon","bio":"Well aquainted with the harshest of deserts. Spend their days searching for treasure hidden beneath vast sand dunes."},
    {"pokemon":"Mudkip", "image":"https://tinyurl.com/2bcy7yqq", "type":"Water","bio":"Trys to invent new games, usually involving a bouncy ball. Swears this time their game will be a sensation."},
    {"pokemon":"Torchic", "image":"https://tinyurl.com/2dqdpzun", "type":"Fire","bio":"Is the leading causes for melting icebergs. Enjoys watching polar bears float away on rogue rafts of ice."},
    {"pokemon":"Treecko", "image":"https://tinyurl.com/26xknvr9", "type":"Grass","bio":"Has an army of regular geckos. Plans to conquer the chameleon kingdom 'when the time is right'."},
    {"pokemon":"Torterra", "image":"https://tinyurl.com/2bqwjfmn", "type":"Grass/Ground","bio":"Collects and carrys myriad exocit animals on its giant shell."},
    {"pokemon":"Empoleon", "image":"https://tinyurl.com/2arrzmyb", "type":"Water/Steel","bio":"Hunting down Torchic for their continued desctruction of the polar icecaps."},
    {"pokemon":"Luxray", "image":"https://tinyurl.com/2yuhlkbg", "type":"Electric","bio":"Competes on the racetrack, jockeyed by a capuchin monkey."},
    {"pokemon":"Staraptor", "image":"https://tinyurl.com/2bp5fbsl", "type":"Normal/Flying","bio":"Broods on their perch and pecks at anyone who looks at them funny."},
    {"pokemon":"Gible", "image":"https://tinyurl.com/259muzhf", "type":"Dragon/Ground","bio":"Leader of a barbershop quartet."},
    {"pokemon":"Piplup", "image":"https://tinyurl.com/224h6r7l", "type":"Water","bio":"Believes ice sculptures are the next big thing."},
    {"pokemon":"Chimchar", "image":"https://tinyurl.com/2y3smyaj", "type":"Fire","bio":"Is the definition of Monkey Business."},
    {"pokemon":"Turtwig", "image":"https://tinyurl.com/29zdmaok", "type":"Grass","bio":"Likes to hide in tall grass and bite any passersby"},
    {"pokemon":"Gallade", "image":"https://tinyurl.com/2dpoer76", "type":"Psychic/Fighting","bio":"Wants to learn to spin like a spinning top."},
    {"pokemon":"Glaceon", "image":"https://tinyurl.com/22xvc2t8", "type":"Ice","bio":"Has lost survivor four times."},
    {"pokemon":"Leafeon", "image":"https://tinyurl.com/24vezoyo", "type":"Grass","bio":"Town mascot and owner of the local pub."},
    {"pokemon":"Absol", "image":"https://tinyurl.com/24rad9j2", "type":"Dark","bio":"Likes to hunt down bats. Thinks any one of them could be Dracula in the making."},
    {"pokemon":"Crobat", "image":"https://tinyurl.com/2b6qjxz4", "type":"Poison/Flying","bio":"On the run from Absol. Is definitely not Dracula in the making."},
    {"pokemon":"Kingdra", "image":"https://tinyurl.com/26kmp4x7", "type":"Water/Dragon","bio":"Star of the show at their aquarium. Idolizes Dory."},
    {"pokemon":"Slowbro", "image":"https://tinyurl.com/27zwg7gk", "type":"Water/Psychic","bio":"Hates the implications of their name. Actions have only cemented the moniker."},
    {"pokemon":"Slowking", "image":"https://tinyurl.com/24b4bm7p", "type":"Water/Psychic","bio":"Has accepted their name and now claims soveriegnity over the Slowbros."},
    {"pokemon":"Ampharos", "image":"https://tinyurl.com/255hsv5p", "type":"Electric","bio":"Likes to dance on the corners of busy streets. Dance routine includes waving their arms and waving a little faster."},
    {"pokemon":"Typhlosion", "image":"https://tinyurl.com/2bl85ynf", "type":"Fire","bio":"Likes to take leisurely swims in pools of magma."},
    {"pokemon":"Feraligatr", "image":"https://tinyurl.com/26r6kdpj", "type":"Water","bio":"Plays the standing bass at their local bar."},
    {"pokemon":"Meganium", "image":"https://tinyurl.com/2axr2pjy", "type":"Grass","bio":"Likes to help gardening with any who share their love for plants."},
    {"pokemon":"Noivern", "image":"https://tinyurl.com/23cowy39", "type":"Flying/Dragon","bio":"Blasts music through their uniquely shaped head as they fly, provoking shaking fists from sleeping neighbors. "},
    {"pokemon":"Houndoom", "image":"https://tinyurl.com/2d8bk69h", "type":"Dark/Fire","bio":"Reason why 'Beware of Dog' signs exist."},
    {"pokemon":"Zygarde", "image":"https://tinyurl.com/2amybtay", "type":"Dragon/Ground","bio":"Brags about being an old soul and how nothing hits like Gregorian Chants"},
    {"pokemon":"Dialga", "image":"https://tinyurl.com/2auuuyc3", "type":"Steel/Dragon","bio":"Often attaches wire coat hangers to head hoping for better reception."},
    {"pokemon":"Palkia", "image":"https://tinyurl.com/25t5o32g", "type":"Water/Dragon","bio":"Missed their calling as a singer for a KISS coverband."},
    {"pokemon":"Rayquaza", "image":"https://tinyurl.com/22726oqh", "type":"Dragon/Flying","bio":"Easily mistaken for an ethernet cable."},
    {"pokemon":"Deoxys", "image":"https://tinyurl.com/26umzj4h", "type":"Psychic","bio":"Enjoys dancing with the wacky waving inflatable tube man."},
    {"pokemon":"Regice", "image":"https://tinyurl.com/2yyveqdu", "type":"Ice","bio":"Arrested for reflecting light off their crystalline form at passing planes."},
    {"pokemon":"Registeel", "image":"https://tinyurl.com/2a2mhlnl", "type":"Steel","bio":"Likes to work out, but always forgets arm day."},
    {"pokemon":"Regirock", "image":"https://tinyurl.com/23ctrguv", "type":"Rock","bio":"A little rough around the edges, but really likes to rock."},
    {"pokemon":"Jirachi", "image":"https://tinyurl.com/27rrnk84", "type":"Steel/Psychic","bio":"Doesn't like to travel, but anything above a light breeze sends them hurtling through the sky."},
    {"pokemon":"Cresselia", "image":"https://tinyurl.com/2ydkvfw4", "type":"Psychic","bio":"Loves to make ice sculptures, but can't scuplt a face without it looking creepy."},
    {"pokemon":"Darkrai", "image":"https://tinyurl.com/2ynndfoh", "type":"Dark","bio":"Spends most days watching dogs chase their own tail."},
    {"pokemon":"Manaphy", "image":"https://tinyurl.com/2yjs2r25", "type":"Water","bio":"Leader of a theives guild made of like minded miscreants."},
    {"pokemon":"Arceus", "image":"https://tinyurl.com/23ef3rvn", "type":"Normal","bio":"Has a bad habit of getting caught in fences."},
    {"pokemon":"Giratina", "image":"https://tinyurl.com/27fwtsdo", "type":"Ghost/Dragon","bio":"Recites slam poetry in the middle of graveyards. On quiet nights, the faint clacking a boney fingers snapping together can be heard after a performance."},
    {"pokemon":"Victini", "image":"https://tinyurl.com/2ddu2lra", "type":"Psychic/Fire","bio":"Plays way too much with matches."},
    {"pokemon":"Mr.Mime", "image":"https://tinyurl.com/2b86wso7", "type":"Psychic/Fairy","bio":"Has eternally trapped themselves in an invisible box. The more they fight against their confines, the smaller the box seems to get."},
    {"pokemon": "Togepi", "image":"https://tinyurl.com/24qa89n4", "type":"Fairy", "bio":"Has head spikes at the perfect level for breaking shins."},
    {"pokemon": "Pancham", "image":"https://tinyurl.com/25nfru88", "type":"Fighting", "bio":"Known to wear sunglasses indoors."},
    {"pokemon": "Aegislash", "image":"https://tinyurl.com/29rqjf6e", "type":"Steel/Ghost", "bio":"Appears to those in the dead of night who are aware but not fully awake. Best friends with your sleep paralysis demon."},
    {"pokemon": "Litten", "image":"https://tinyurl.com/25drhpzb", "type":"Fire", "bio":"Makes sure to kick as much litter out of their litter box as they can."},
    {"pokemon": "Incineroar", "image":"https://tinyurl.com/2yov2sak", "type":"Fire/Dark", "bio":"Float like a cat on steroids, sting like a glowing cattle brand."},
    {"pokemon": "Popplio", "image":"https://tinyurl.com/253efl7j", "type":"Water", "bio":"Stepped up when Rudolph couldn't."},
    {"pokemon": "Primarina", "image":"https://tinyurl.com/2cybvveg", "type":"Water/Fairy", "bio":"Has a 'refined' palette. Refuses to eat anything other than shiny rocks."},
    {"pokemon": "Rowlet", "image":"https://tinyurl.com/2998o5ef", "type":"Grass/Flying", "bio":"Lights are on, but no one is home."},
    {"pokemon": "Decidueye", "image":"https://tinyurl.com/2ahrwmog", "type":"Grass/Ghost", "bio":"Flamenco dancer and wannabe Robin Hood."},
    {"pokemon": "Kommo-o", "image":"https://tinyurl.com/27s673q7", "type":"Dragon/Fighting", "bio":"Every step makes their scales rattle like a mix between jingling keys and dusty bones."},
    {"pokemon": "Salazzle", "image":"https://tinyurl.com/y66zmo99", "type":"Poison/Fire", "bio":"Hopes to be a professional model. Climbs to the tops of skyscapers to show off their modeling poses, hoping a passing helicopter will notice."},
    {"pokemon": "Buzzwole", "image":"https://tinyurl.com/29h93efh", "type":"Bug/Fighting", "bio":"Can go head to head with Larry the Lobster."},
    {"pokemon": "Pheromosa", "image":"https://tinyurl.com/2d9ub9sg", "type":"Bug/Fighting", "bio":"Icon of high fashion until they trip on their own antennae."},
    {"pokemon": "Celesteela", "image":"https://tinyurl.com/2lfd2l82", "type":"Steel/Flying", "bio":"Hopes to bring about a new age with their sentient vaccum cleaners."},
    {"pokemon": "Nihilego", "image":"https://tinyurl.com/24rkjxqk", "type":"Rock/Poison", "bio":"Hiding out in Bikini Bottom, fleeing from the ever relentless Sponge."},
    {"pokemon": "Xurkitree", "image":"https://tinyurl.com/27u7dllh", "type":"Electric", "bio":"Hides among the Christmas trees on display at Home Depot. Is the main reason so many Christmas lights seem to go out for no reason."},
    {"pokemon": "Kartana", "image":"https://tinyurl.com/22efmn53", "type":"Grass/Steel", "bio":"This living oragami warrior gives one mean paper cut."},
    {"pokemon": "Blacephalon", "image":"https://tinyurl.com/27g7slen", "type":"Fire/Ghost", "bio":"Center of any Disco Party and the owner of a prestigious disco night club."},
    {"pokemon": "Tapu Koko", "image":"https://tinyurl.com/2d8cyvro", "type":"Electric/Fairy", "bio":"Can be sighted running around town, banging two halves of a coconut together."},
    {"pokemon": "Tapu Lele", "image":"https://tinyurl.com/2y6vqay9", "type":"Psychic/Fairy", "bio":"Hopes to bring about an eternal winter."},
    {"pokemon": "Tapu Bulu", "image":"https://tinyurl.com/22g9qqw5", "type":"Grass/Fairy", "bio":"Many a matador has looked to fight them, but few have proven skilled enough."},
    {"pokemon": "Tapu Fini", "image":"https://tinyurl.com/22poyhkr", "type":"Water/Fairy", "bio":"Goes into unpredictable blood rage, jumping out of the water to skewer unsuspecting sailors."},
    {"pokemon": "Lycanroc", "image":"https://tinyurl.com/2bc36tda", "type":"Rock", "bio":"Searching for the center of the earth. The most progress they have made is the destruction of a few gardens as they searched for the best digging spot."},
    {"pokemon": "Oricorio", "image":"https://tinyurl.com/2xmga4fh", "type":"Fire/Flying", "bio":"A master at dancing the tango and uses their fire to add dazzling flair."},
    {"pokemon": "Wishiwashi", "image":"https://tinyurl.com/25yvrrru", "type":"Water", "bio":"Curates a collection of highly unique and questionably legal artifacts."},
    {"pokemon": "Mimikyu", "image":"https://tinyurl.com/2498bodf", "type":"Ghost/Fairy", "bio":"Went as Pikachu for Halloween but hasn't been able to take off the costume."},
    {"pokemon": "Toxtricity", "image":"https://tinyurl.com/26fn6h4d", "type":"Electric/Poison", "bio":"Lead guitarist for their mediocre garage band."},
    {"pokemon": "Rillaboom", "image":"https://tinyurl.com/2bf3zqxb", "type":"Grass", "bio":"Thought they were destined to be the king of the jungle, but then they met Grookey."},
    {"pokemon": "Cinderace", "image":"https://tinyurl.com/2626znp4", "type":"Fire", "bio":"Often gets into kicking matches with kangaroos."},
    {"pokemon": "Inteleon", "image":"https://tinyurl.com/23zblqne", "type":"Water", "bio":"Below room temperature IQ and a personality to match."},
    {"pokemon": "Eternatus", "image":"https://tinyurl.com/24euqgtt", "type":"Poison/Dragon", "bio":"Likes to comb through sandy beaches looking for buried treasure."},
    {"pokemon": "Dragapult", "image":"https://tinyurl.com/2y8mnlds", "type":"Dragon/Ghost", "bio":"Entertains others by juggling geckos in the air."},
    {"pokemon": "Corviknight", "image":"https://tinyurl.com/2csv47oa", "type":"Flying/Steel", "bio":"Last living knight of the Avian Table."},
    {"pokemon": "Drednaw", "image":"https://tinyurl.com/23sjdspx", "type":"Water/Rock", "bio":"Plays the mouth harp on weekends and bongos on holidays."},
    {"pokemon": "Centiskorch", "image":"https://tinyurl.com/2yswun7r", "type":"Fire/Bug", "bio":"Always there when someone needs a lighter."},
    {"pokemon": "Polteageist", "image":"https://tinyurl.com/2ybkw866", "type":"Ghost", "bio":"Their ghostly tea can cause hallucinations in those unlucky enough to take a sip."},
    {"pokemon": "Hatterene", "image":"https://tinyurl.com/26ad47vd", "type":"Psychic/Fairy", "bio":"Quite kind but can prove to be wrathful when provoked."},
    {"pokemon": "Grimmsnarl", "image":"https://tinyurl.com/24blupj6", "type":"Dark/Fairy", "bio":"Self proclaimed king of the goblins."},
    {"pokemon": "Alcremie", "image":"https://tinyurl.com/269e9r9a", "type":"Fairy", "bio":"Cute mascot for bakeries everywhere."},
    {"pokemon": "Zarude", "image":"https://tinyurl.com/2a6fhtv8", "type":"Dark/Grass", "bio":"Sibling to terrors known as the gremlins."},
    {"pokemon": "Kubfu", "image":"https://tinyurl.com/22ww3j7l", "type":"Fighting", "bio":"Wants to be the best karate master there is. White belt is only a starting point."},
    {"pokemon": "Urshifu", "image":"https://tinyurl.com/23bp4w9w", "type":"Fighting/Dark", "bio":"Breaks cinder blocks with only a look and spars with their hands tied."},
    {"pokemon": "Regieleki", "image":"https://tinyurl.com/28um6vjw", "type":"Electric", "bio":"Professional bug zapper."},
    {"pokemon": "Regidrago", "image":"https://tinyurl.com/29casdqz", "type":"Dragon", "bio":"Hides under the sand and snaps passersby like a bear trap."},
    {"pokemon": "Calyrex", "image":"https://tinyurl.com/22krzsnu", "type":"Psychic/Grass", "bio":"Seen as the fifth rider of the apocalypse and leaves terror in their wake."},
    {"pokemon": "Zacian", "image":"https://tinyurl.com/25e786vd", "type":"Fairy/Steel", "bio":"Trained by and admires the Great Gray Wolf Sif."},
    {"pokemon": "Zamazenta", "image":"https://tinyurl.com/25lgom7l", "type":"Fighting/Steel", "bio":"Shield of the vanguard, always at the forefront when hunting abyssal horrors."},
    {"pokemon": "Glastrier", "image":"https://tinyurl.com/28wzwk24", "type":"Ice", "bio":"A steed without a rider, always hopeful in their search."},
    {"pokemon": "Spectrier", "image":"https://tinyurl.com/2ykgl7c7", "type":"Ghost", "bio":"Searched for ages, never finding their destined rider. Mournful determination is the only thing keeping this spectre from passing on."},
    {"pokemon": "Copperajah", "image":"https://tinyurl.com/2y4s95kh", "type":"Steel", "bio":"Their fear of mice is so great that they have devoted their life to hunting the tiny, foul monsters."},
    {"pokemon": "Sandaconda", "image":"https://tinyurl.com/2daw568a", "type":"Ground", "bio":"Keeps clumsily tying themselves into knots."},
    {"pokemon": "Cramorant", "image":"https://tinyurl.com/27lkudbe", "type":"Flying/Water", "bio":"Definition of bird brained."},
    {"pokemon": "Dracovish", "image":"https://tinyurl.com/2xuo2pkf", "type":"Water/Dragon", "bio":"Uses their hard head to crack walnuts and sometimes boulders."},
    {"pokemon": "Arctozolt", "image":"https://tinyurl.com/27eussds", "type":"Electric/Ice", "bio":"An ugly crier and not so subtle about it."},
    {"pokemon": "Eiscue", "image":"https://tinyurl.com/24nfsbhz", "type":"Ice", "bio":"When frightened, sticks their head into the ice like an ostrich."},
    {"pokemon": "Duraludon", "image":"https://tinyurl.com/2cx6dyqq", "type":"Steel/Dragon", "bio":"Projectile used in prototype gauss weapons."},
    {"pokemon": "Obstagoon", "image":"https://tinyurl.com/2d3ktc7x", "type":"Dark/Normal", "bio":"Thinks hysterical laughing is high tier singing."},
    {"pokemon": "Morpeko", "image":"https://tinyurl.com/277ap8j8", "type":"Electric/Dark", "bio":"Sticks to Pikachu like a remora to a shark."},
    {"pokemon": "Indeedee", "image":"https://tinyurl.com/279fggvm", "type":"Psychic/Normal", "bio":"Aspiring ballerina and great at Hula Hooping."},
    {"pokemon": "Dracozolt", "image":"https://tinyurl.com/23red6un", "type":"Electric/Dragon", "bio":"Is really just wearing the bottom half of an inflatable T-Rex costume."},
    {"pokemon": "Appletun", "image":"https://tinyurl.com/227239zb", "type":"Grass/Dragon", "bio":"Breathes fire that smells of applie pie and flaming death."},
    {"pokemon": "Cufant", "image":"https://tinyurl.com/27erb4to", "type":"Steel", "bio":"Their trunk is great at smashing vile vermin."},
    {"pokemon": "Thievul", "image":"https://tinyurl.com/22vgfprw", "type":"Dark", "bio":"A head member of the local theives guild and aspires to own it all."},
    {"pokemon": "Dubwool", "image":"https://tinyurl.com/23erctxv", "type":"Normal", "bio":"Has a mean heabutt and applies it liberally."},
    {"pokemon": "Boltund", "image":"https://tinyurl.com/2awtq5pl", "type":"Electric", "bio":"Can play fetch for weeks on end, fast as lighting."},
    {"pokemon": "Toxel", "image":"https://tinyurl.com/233ybfvk", "type":"Electric/Poison", "bio":"Tiny guy with a big brain and gloomy disposition."},
    {"pokemon": "Greedent", "image":"https://tinyurl.com/25zcodok", "type":"Normal", "bio":"Boasts great agility and bod weight from a life of stealing other squirrels' stashes of nuts."},
    {"pokemon": "Frosmoth", "image":"https://tinyurl.com/22t2f57o", "type":"Ice/Bug", "bio":"Can eat entire wardrobes of silk clothing."},
    {"pokemon": "Snom", "image":"https://tinyurl.com/2352zxqu", "type":"Ice/Bug", "bio":"The immortal snail isn't real, but this little one is relentless."},
    {"pokemon": "Sinistea", "image":"https://tinyurl.com/2cclwgad", "type":"Ghost", "bio":"The beginning brew of crazy liquid."},
    {"pokemon": "Yamper", "image":"https://tinyurl.com/2bv2wzou", "type":"Electric", "bio":"The cutest little pup with a zap in every bark."},
    {"pokemon": "Rolycoly", "image":"https://tinyurl.com/2dfrlxua", "type":"Rock", "bio":"A minion of the mines, with blood of coal and stone."},
    {"pokemon": "Hatenna", "image":"https://tinyurl.com/27nuh4zh", "type":"Psychic", "bio":"An initiate of the school of sleepy spells."},
    {"pokemon": "Rookidee", "image":"https://tinyurl.com/27ddu9nl", "type":"Flying", "bio":"Mean as a blue jay and takes trophies juts the same."},
    {"pokemon": "Dreepy", "image":"https://tinyurl.com/2dlkkgus", "type":"Dragon/Ghost", "bio":"Eager to make friends and always has a happy word for those in need."},
    {"pokemon": "Clobbopus", "image":"https://tinyurl.com/2dfv5oee", "type":"Fighting", "bio":"King of the boxing ring and all-round champion. Secretly uses ink to cheat during fights."},
    {"pokemon": "Grapploct", "image":"https://tinyurl.com/27mafepn", "type":"Fighting", "bio":"Likes to recreate the double eye poke from the Three Stooges."},
    {"pokemon": "Carkol", "image":"https://tinyurl.com/22mfvar9", "type":"Rock/Fire", "bio":"Transports the coal and ore from the mines, riding the cart tracks with reckless abandon."},
    {"pokemon": "Gossifleur", "image":"https://tinyurl.com/26nqlu82", "type":"Grass", "bio":"Allergic to flowers."},
    {"pokemon": "Eldegoss", "image":"https://tinyurl.com/233neuvc", "type":"Grass", "bio":"Uses head to float around like a hot air balloon."},
    {"pokemon": "Wooloo", "image":"https://tinyurl.com/26loj6go", "type":"Normal", "bio":"Rools around in a little ball of wool."},
    {"pokemon": "Chewtle", "image":"https://tinyurl.com/2bl4vfcm", "type":"Water", "bio":"Known ankle biter and notorious knee nibbler."},
    {"pokemon": "Silicobra", "image":"https://tinyurl.com/29fzdcqn", "type":"Ground", "bio":"Their fangs never grew in, so they spit venom instead."},
    {"pokemon": "Arrokuda", "image":"https://tinyurl.com/2bae96gz", "type":"Water", "bio":"Their big grin only holds three teeth, but that doesn't stop them from smiling."},
    {"pokemon": "Barraskewda", "image":"https://tinyurl.com/2cvpdhzx", "type":"Water", "bio":"Hunts using their head like a spear."},
    {"pokemon": "Probopass", "image": "https://tinyurl.com/2xubwu5x", "type": "Rock/Steel", "bio": "With a massive nose and mustache, Probopass can direct metal filings toward enemies. Looks like a rock who takes mustache grooming very seriously."},
    {"pokemon": "Lickilicky", "image": "https://tinyurl.com/27vu9szh", "type": "Normal", "bio": "An evolution of Lickitung, it has an extra-long tongue perfect for slurping up food – and maybe even its opponents!"},
    {"pokemon": "Stunfisk", "image": "https://tinyurl.com/2anomsp8", "type": "Ground/Electric", "bio": "Looking like a pancake gone wrong, this flat fish hides in mud and delivers shocking surprises."},
    {"pokemon": "Bidoof", "image": "https://tinyurl.com/28gz33df", "type": "Normal", "bio": "A beaver with big teeth and a big heart. Often underestimated, Bidoof is surprisingly lovable despite its goofy grin."},
    {"pokemon": "Spoink", "image": "https://tinyurl.com/22e8q8jv", "type": "Psychic", "bio": "A bouncing piggy Pokémon that has to keep springing on its tail – or else! With every bounce, it looks more determined than ever."},
    {"pokemon": "Swoobat", "image": "https://tinyurl.com/27ks5lcf", "type": "Psychic/Flying", "bio": "A bat with a heart-shaped nose that radiates happiness and sometimes even ultrasonic attacks."},
    {"pokemon": "Alolan Exeggutor", "image": "https://tinyurl.com/2agn6cho", "type": "Grass/Dragon", "bio": "An extremely tall, tropical Exeggutor with a very long neck that could easily poke the clouds. Makes other Pokémon look up in awe – or confusion."},
    {"pokemon": "Bruxish", "image": "https://tinyurl.com/27byzedc", "type": "Water/Psychic", "bio": "A colorful fish with way too many teeth and a fashion sense that’s hard to miss. Bruxish is flashy, bold, and maybe a little vain."},
    {"pokemon": "Woobat", "image": "https://tinyurl.com/25vgehts", "type": "Psychic/Flying", "bio": "A fluffy bat with a big heart (literally, on its nose). It loves to swoop around in caves spreading love and a little chaos."},
    {"pokemon": "Farfetch’d", "image": "https://tinyurl.com/22maw8hh", "type": "Normal/Flying", "bio": "A quirky bird who carries a leek as its weapon of choice, as if ready to start a cooking show instead of a battle."},
    {"pokemon": "Klefki", "image": "https://tinyurl.com/22n8yaez", "type": "Steel/Fairy", "bio": "A set of keys that jingles with excitement whenever it finds more keys to collect. It’s a locksmith’s best – or worst – friend."},
    {"pokemon": "Wobbuffet", "image": "https://tinyurl.com/27mkvwsw", "type": "Psychic", "bio": "A Pokémon that just stands there taking hits. With a smile that says, ‘Hit me again, I dare you.’"},
    {"pokemon": "Delibird", "image": "https://tinyurl.com/245nw78t", "type": "Ice/Flying", "bio": "A red-and-white bird that looks ready for Christmas, carrying a sack with mysterious ‘presents’ that may just explode."},
    {"pokemon": "Ludicolo", "image": "https://tinyurl.com/28b42td9", "type": "Water/Grass", "bio": "With a pineapple-like hat and a love for dance, Ludicolo grooves to its own beat, bringing the party to every battle."}

]

natures_list = ["Hardy", "Lonely", "Brave", "Adamant", "Naughty", "Bold", "Docile", "Relaxed", "Impish", "Lax", "Timid", "Hasty", "Serious", "Jolly", "Naive", "Modest", "Mild", "Quiet", "Bashful", "Rash", "Calm", "Gentle", "Sassy", "Careful", "Quirky"]
